// AuthActions
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

// UpdateActions
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
export const UPDATE_LATER = 'UPDATE_LATER';
export const START_UPDATE = 'START_UPDATE';
export const SET_UPDATE_STATUS = 'SET_UPDATE_STATUS';
export const UPDATE_FAILED = 'UPDATE_FAILED';
export const APP_VERSION_CHANGED = 'APP_VERSION_CHANGED';

//UtilityActions
export const TOGGLE_LAYOUT_KEYBOARD_VISIBLE = 'TOGGLE_LAYOUT_KEYBOARD_VISIBLE';
export const CLOSE_KEYBOARD = 'CLOSE_KEYBOARD';
export const UPDATE_NETWORK_STATUS = ' UPDATE_NETWORK_STATUS';
export const ALERT_MESSAGE = 'ALERT_MESSAGE';
export const CLEAR_ALERT_MESSAGE = ' CLEAR_ALERT_MESSAGE';

// SettingsActions
export const TOGGLE_SETTINGS_MENU = 'TOGGLE_SETTINGS_MENU';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const REPORT_ERROR_START = 'REPORT_ERROR_START ';
export const REPORT_ERROR_SUCCESS = 'REPORT_ERROR_SUCCESS';
export const REPORT_ERROR_FAIL = 'REPORT_ERROR_FAIL';
export const HIDE_REPORTS_MODAL = 'HIDE_REPORTS_MODAL';

// DataActions
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const SET_ONSITE_LIST_LOADING = 'SET_ONSITE_LIST_LOADING';
export const SET_ONSITE_LIST = 'SET_ONSITE_LIST';

// FormActions
export const CLEAR_FORM = 'CLEAR_FORM';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const ADD_NEW_LPN = 'ADD_NEW_LPN';
export const ADD_NEW_COMPANY = 'ADD_NEW_COMPANY';
export const ADD_NEW_DRIVER = 'ADD_NEW_DRIVER';
export const ADD_NEW_PASSENGERS = 'ADD_NEW_PASSENGERS';
export const FORM_INCOMPLETE_ERROR = 'FORM_INCOMPLETE_ERROR';
export const SAVE_ADDITIONAL_PHOTO = 'SAVE_ADDITIONAL_PHOTO';
export const REMOVE_PHOTO_INSTANCE = 'REMOVE_PHOTO_INSTANCE';
export const TAKE_PHOTO_SUCCESS = 'TAKE_PHOTO_SUCCESS';

// ModalActions
export const SHOW_ADD_PASSENGER_MODAL = 'SHOW_ADD_PASSENGER_MODAL';
export const HIDE_ADD_PASSENGER_MODAL = 'HIDE_ADD_PASSENGER_MODAL';
export const SHOW_ADD_COMMENT_MODAL = 'SHOW_ADD_COMMENT_MODAL';
export const HIDE_ADD_COMMENT_MODAL = 'HIDE_ADD_COMMENT_MODAL';

// CameraActions
export const TOGGLE_FLASH = 'TOGGLE_FLASH';
export const MODIFY_EXISTING_PHOTO = 'MODIFY_EXISTING_PHOTO';
export const SHOW_CAMERA = 'SHOW_CAMERA';
export const HIDE_CAMERA = 'HIDE_CAMERA';
export const SHOW_CAMERA_MODIFIED = 'SHOW_CAMERA_MODIFIED';

// EventActions
export const SAVE_EVENT = 'SAVE_EVENT';
export const CLEAR_EVENT_SAVE_MODAL = 'CLEAR_EVENT_SAVE_MODAL';

// SYNC
export const SYNC_DATA = 'SYNC_DATA';
export const SET_FORCE_SYNC = 'SET_FORCE_SYNC';
