// AuthActions
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHECK_PENDING_UPLOADS = 'CHECK_PENDING_UPLOADS';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

// UpdateActions
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const APPLY_UPDATE = 'APPLY_UPDATE';
export const RESET_REDUCER_GROUP = 'RESET_REDUCER_GROUP';

//UtilityActions
export const TOGGLE_LAYOUT_KEYBOARD_VISIBLE = 'TOGGLE_LAYOUT_KEYBOARD_VISIBLE';
export const CLOSE_KEYBOARD = 'CLOSE_KEYBOARD';
export const UPDATE_NETWORK_STATUS = ' UPDATE_NETWORK_STATUS';

// SettingsActions
export const TOGGLE_SETTINGS_MENU = 'TOGGLE_SETTINGS_MENU';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const REPORT_ERROR_START = 'REPORT_ERROR_START ';
export const REPORT_ERROR_SUCCESS = 'REPORT_ERROR_SUCCESS';
export const REPORT_ERROR_FAIL = 'REPORT_ERROR_FAIL';
export const HIDE_REPORTS_MODAL = 'HIDE_REPORTS_MODAL';

// DataActions
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const SET_ONSITE_COUNT = 'SET_ONSITE_COUNT';
export const SET_UPLOADING = 'SET_UPLOADING';

// FormActions
export const CLEAR_FORM = 'CLEAR_FORM';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const ADD_NEW_LPN = 'ADD_NEW_LPN';
export const ADD_NEW_COMPANY = 'ADD_NEW_COMPANY';
export const ADD_NEW_DRIVER = 'ADD_NEW_DRIVER';
export const ADD_NEW_PASSENGERS = 'ADD_NEW_PASSENGERS';
export const ADD_NEW_LPN_LOCAL = 'ADD_NEW_LPN_LOCAL';
export const ADD_NEW_COMPANY_LOCAL = 'ADD_NEW_COMPANY_LOCAL';
export const ADD_NEW_DRIVER_LOCAL = 'ADD_NEW_DRIVER_LOCAL';
export const FORM_INCOMPLETE_ERROR = 'FORM_INCOMPLETE_ERROR';
export const SAVE_ADDITIONAL_PHOTO = 'SAVE_ADDITIONAL_PHOTO';
export const REMOVE_PHOTO_INSTANCE = 'REMOVE_PHOTO_INSTANCE';
export const TAKE_PHOTO_SUCCESS = 'TAKE_PHOTO_SUCCESS';

// ModalActions
export const SHOW_ADD_PASSENGER_MODAL = 'SHOW_ADD_PASSENGER_MODAL';
export const HIDE_ADD_PASSENGER_MODAL = 'HIDE_ADD_PASSENGER_MODAL';
export const SHOW_ADD_COMMENT_MODAL = 'SHOW_ADD_COMMENT_MODAL';
export const HIDE_ADD_COMMENT_MODAL = 'HIDE_ADD_COMMENT_MODAL';

// CameraActions
export const TOGGLE_FLASH = 'TOGGLE_FLASH';
export const SAVE_MODIFIED_PHOTO = 'SAVE_MODIFIED_PHOTO';
export const MODIFY_EXISTING_PHOTO = 'MODIFY_EXISTING_PHOTO';
export const SHOW_CAMERA = 'SHOW_CAMERA';
export const HIDE_CAMERA = 'HIDE_CAMERA';
export const SHOW_CAMERA_MODIFIED = 'SHOW_CAMERA_MODIFIED';

// EventActions
export const UPLOAD_EVENT_START = 'UPLOAD_EVENT_START';
export const UPLOAD_EVENT_SUCCESS = 'UPLOAD_EVENT_SUCCESS';
export const UPLOAD_EVENT_FAIL = 'UPLOAD_EVENT_FAIL';
export const UPLOAD_LOCAL_EVENT_SUCCESS = 'UPLOAD_LOCAL_EVENT_SUCCESS';
export const SAVE_EVENT = 'SAVE_EVENT';
export const INCREMENT_LOCAL_ONSITE_COUNT = 'INCREMENT_LOCAL_ONSITE_COUNT';
export const DECREMENT_LOCAL_ONSITE_COUNT = 'DECREMENT_LOCAL_ONSITE_COUNT';
export const CLEAR_EVENT_SAVE_MODAL = 'CLEAR_EVENT_SAVE_MODAL';

// SYNC
export const SYNC_DATA = 'SYNC_DATA';
export const REPORT_ERROR = 'REPORT_ERROR';
export const EVALUATE_TOUCH_EVENT = 'EVALUATE_TOUCH_EVENT';
export const APP_INTERACTION_UPDATE = 'APP_INTERACTION_UPDATE';
